In [13]:
import umap.umap_ as umap
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import random
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy.stats import chi2_contingency
import scipy.stats as stats
import math
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [14]:
data = pd.read_csv('edited_data.csv')
data[data < 0] = 0
data["date"] = pd.to_datetime(data["Date"], format="%Y%m%d")
data["Month"] = data["date"].dt.month
data['TRAFFIC'] = data['TRAFFIC'].map(
    lambda x: math.log(x) if (pd.notnull(x) and x > 0) else x
)
# data['Vehicles'] = data['Vehicles'].map(
#     lambda x: math.log(x) if (pd.notnull(x) and x > 0) else x
# )
# data['SNOW_DAY_SUM'] = data['SNOW_DAY_SUM'].map(
#     lambda x: math.log(x) if (pd.notnull(x) and x > 0) else x
# )
data.head()

,Unnamed: 0,Date,Direction,Time,TRAFFIC,PRCP,SNOW,SNWD,SNOW_DAY_SUM,Vehicles,Driver Age,Condition_Code,MorF,DayOfWeek,date,Month
0,0,20140101,1,0,4.624973,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1
1,1,20140101,0,0,4.875197,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1
2,2,20140101,1,1,4.510860,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1
3,3,20140101,0,1,5.087596,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1
4,4,20140101,1,2,4.454347,0.12,1.9,13.0,1.9,1.0,26.0,0.0,0.0,3,2014-01-01,1

In [15]:
Month_codots = {
        1: 3, 2:1, 3:2, 4:4, 12: 5, 5:6, 11: 7, 6: 8, 7: 12, 8: 10, 9: 11, 10: 9
    }
k = {1,2,3,4,5,6}
data['WeightedMonth'] = data['Month'].map(lambda x: Month_codots[x])
data_with_snow = data[data['SNOW'] > 0]
data_with_no_snow = data[data['SNOW'] == 0]
data_with_no_snow.head()

,Unnamed: 0,Date,Direction,Time,TRAFFIC,PRCP,SNOW,SNWD,SNOW_DAY_SUM,Vehicles,Driver Age,Condition_Code,MorF,DayOfWeek,date,Month,WeightedMonth
98,98,20140103,1,0,4.804021,0.0,0.0,12.0,2.4,0.0,0.0,0.0,0.0,5,2014-01-03,1,3
99,99,20140103,0,0,5.093750,0.0,0.0,12.0,2.4,0.0,0.0,0.0,0.0,5,2014-01-03,1,3
100,100,20140103,1,1,4.382027,0.0,0.0,12.0,2.4,0.0,0.0,0.0,0.0,5,2014-01-03,1,3
101,101,20140103,0,1,4.682131,0.0,0.0,12.0,2.4,0.0,0.0,0.0,0.0,5,2014-01-03,1,3
102,102,20140103,1,2,4.219508,0.0,0.0,12.0,2.4,0.0,0.0,0.0,0.0,5,2014-01-03,1,3

In [16]:
data_with_no_snow = data_with_no_snow[data_with_no_snow['WeightedMonth'].isin(k)]
data_with_snow["Time"] = data_with_snow["Time"].astype("category")
data_with_snow["Month"] = data_with_snow["Month"].astype("category")
data_with_snow["DayOfWeek"] = data_with_snow["DayOfWeek"].astype("category")
data_with_no_snow["Time"] = data_with_no_snow["Time"].astype("category")
data_with_no_snow["Month"] = data_with_no_snow["Month"].astype("category")
data_with_no_snow["DayOfWeek"] = data_with_no_snow["DayOfWeek"].astype("category")
data_with_snow.head()

C:\Users\wsach\AppData\Local\Temp\ipykernel_28904\897346955.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_snow["Time"] = data_with_snow["Time"].astype("category")
C:\Users\wsach\AppData\Local\Temp\ipykernel_28904\897346955.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_snow["Month"] = data_with_snow["Month"].astype("category")
C:\Users\wsach\AppData\Local\Temp\ipykernel_28904\897346955.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_snow["DayOfWeek"] = data_with_snow["DayOfWeek"].astype("category")

,Unnamed: 0,Date,Direction,Time,TRAFFIC,PRCP,SNOW,SNWD,SNOW_DAY_SUM,Vehicles,Driver Age,Condition_Code,MorF,DayOfWeek,date,Month,WeightedMonth
0,0,20140101,1,0,4.624973,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1,3
1,1,20140101,0,0,4.875197,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1,3
2,2,20140101,1,1,4.510860,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1,3
3,3,20140101,0,1,5.087596,0.12,1.9,13.0,1.9,0.0,0.0,0.0,0.0,3,2014-01-01,1,3
4,4,20140101,1,2,4.454347,0.12,1.9,13.0,1.9,1.0,26.0,0.0,0.0,3,2014-01-01,1,3

In [17]:
ols_snow = smf.ols(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_snow
).fit()

print(ols_snow.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   R-squared:                       0.841
Model:                            OLS   Adj. R-squared:                  0.841
Method:                 Least Squares   F-statistic:                     3929.
Date:                Fri, 05 Dec 2025   Prob (F-statistic):               0.00
Time:                        10:15:08   Log-Likelihood:                -24596.
No. Observations:               36324   AIC:                         4.929e+04
Df Residuals:                   36274   BIC:                         4.972e+04
Df Model:                          49
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    4.9841      0.016    319.059      0.000       4.953       5.015
C(Time)[T.1]                -0.3057      0.017    -17.587      0.000      -0.340      -0.272
C(Time)[T.2]                -0.4799      0.017    -27.572      0.000      -0.514      -0.446
C(Time)[T.3]                -0.4199      0.017    -24.131      0.000      -0.454      -0.386
C(Time)[T.4]                -0.0466      0.017     -2.678      0.007      -0.081      -0.012
C(Time)[T.5]                 0.7138      0.017     41.069      0.000       0.680       0.748
C(Time)[T.6]                 1.5398      0.017     88.695      0.000       1.506       1.574
C(Time)[T.7]                 2.0452      0.017    118.132      0.000       2.011       2.079
C(Time)[T.8]                 2.2166      0.017    127.904      0.000       2.183       2.251
C(Time)[T.9]                 2.3347      0.017    134.423      0.000       2.301       2.369
C(Time)[T.10]                2.4298      0.017    140.081      0.000       2.396       2.464
C(Time)[T.11]                2.4832      0.017    143.115      0.000       2.449       2.517
C(Time)[T.12]                2.4853      0.017    143.105      0.000       2.451       2.519
C(Time)[T.13]                2.5351      0.017    146.273      0.000       2.501       2.569
C(Time)[T.14]                2.5901      0.017    149.316      0.000       2.556       2.624
C(Time)[T.15]                2.6040      0.017    149.985      0.000       2.570       2.638
C(Time)[T.16]                2.5732      0.017    148.148      0.000       2.539       2.607
C(Time)[T.17]                2.4184      0.017    139.185      0.000       2.384       2.452
C(Time)[T.18]                2.1557      0.017    124.182      0.000       2.122       2.190
C(Time)[T.19]                1.8192      0.017    104.733      0.000       1.785       1.853
C(Time)[T.20]                1.5247      0.017     87.744      0.000       1.491       1.559
C(Time)[T.21]                1.2032      0.017     69.210      0.000       1.169       1.237
C(Time)[T.22]                0.8195      0.017     47.086      0.000       0.785       0.854
C(Time)[T.23]                0.3894      0.017     22.382      0.000       0.355       0.423
C(WeightedMonth)[T.2]        0.0482      0.009      5.166      0.000       0.030       0.067
C(WeightedMonth)[T.3]       -0.0481      0.009     -5.520      0.000      -0.065      -0.031
C(WeightedMonth)[T.4]       -0.1628      0.010    -16.568      0.000      -0.182      -0.144
C(WeightedMonth)[T.5]       -0.0283      0.009     -3.198      0.001      -0.046      -0.011
C(WeightedMonth)[T.6]       -0.2090      0.012    -17.550      0.000      -0.232      -0.186
C(WeightedMonth)[T.7]       -0.2062      0.009    -21.790      0.000      -0.225      -0.188
C(WeightedMonth)[T.8]        0.1236      0.049      2.509      0.012       0.027       0.220
C(WeightedMonth)[T.9]       -0.1841      0.012    -14.908      0.000      -0.208      -0.160
C(WeightedMonth)[T.11]       0.0620      0.040      1.534      0.125      -0.017       0.141
C(DayOfWeek)[T.2]           -0.1222      0.009    -12.877      0.000      -0.141      -0.104
C(DayOfWeek)[T.3]           -0.0604      0.010     -6.226      0.000      -0.079      -0.041
C(DayOfWeek)[T.4]            0.0444      0.010      4.657      0.000       0.026       0.063
C(DayOfWeek)[T.5]            0.2546      0.009     26.875      0.000       0.236       0.273
C(DayOfWeek)[T.6]            0.2012      0.009     21.263      0.000       0.183       0.220
C(DayOfWeek)[T.7]            0.1460      0.010     14.687      0.000       0.126       0.165
C(Condition_Code)[T.1.0]    -0.0166      0.056     -0.294      0.768      -0.127       0.094
C(Condition_Code)[T.2.0]     0.1429      0.128      1.120      0.263      -0.107       0.393
C(Condition_Code)[T.3.0]    -0.0823      0.021     -3.911      0.000      -0.124      -0.041
C(Condition_Code)[T.4.0]    -0.0234      0.119     -0.196      0.844      -0.257       0.210
C(Condition_Code)[T.5.0]    -0.2364      0.042     -5.630      0.000      -0.319      -0.154
C(Condition_Code)[T.6.0]    -0.2703      0.022    -12.187      0.000      -0.314      -0.227
C(Condition_Code)[T.7.0]    -0.2944      0.043     -6.908      0.000      -0.378      -0.211
C(Condition_Code)[T.8.0]    -0.2155      0.075     -2.855      0.004      -0.363      -0.068
C(Direction)[T.1]           -0.1438      0.005    -28.752      0.000      -0.154      -0.134
SNOW_DAY_SUM                 0.0003      0.000      0.555      0.579      -0.001       0.001
SNOW                        -0.0284      0.001    -20.129      0.000      -0.031      -0.026
==============================================================================
Omnibus:                    17339.594   Durbin-Watson:                   2.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           641765.418
Skew:                          -1.639   Prob(JB):                         0.00
Kurtosis:                      23.329   Cond. No.                         471.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
ols_no_snow = smf.ols(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_no_snow
).fit()

print(ols_no_snow.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   R-squared:                       0.883
Model:                            OLS   Adj. R-squared:                  0.883
Method:                 Least Squares   F-statistic:                     8899.
Date:                Fri, 05 Dec 2025   Prob (F-statistic):               0.00
Time:                        10:15:09   Log-Likelihood:                -25535.
No. Observations:               51940   AIC:                         5.116e+04
Df Residuals:                   51895   BIC:                         5.156e+04
Df Model:                          44
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    4.9747      0.011    460.796      0.000       4.954       4.996
C(Time)[T.1]                -0.3303      0.012    -27.406      0.000      -0.354      -0.307
C(Time)[T.2]                -0.5141      0.012    -42.666      0.000      -0.538      -0.490
C(Time)[T.3]                -0.4076      0.012    -33.852      0.000      -0.431      -0.384
C(Time)[T.4]                 0.0037      0.012      0.311      0.756      -0.020       0.027
C(Time)[T.5]                 0.7479      0.012     62.079      0.000       0.724       0.772
C(Time)[T.6]                 1.5224      0.012    126.510      0.000       1.499       1.546
C(Time)[T.7]                 2.0104      0.012    167.019      0.000       1.987       2.034
C(Time)[T.8]                 2.2191      0.012    184.322      0.000       2.196       2.243
C(Time)[T.9]                 2.3597      0.012    195.833      0.000       2.336       2.383
C(Time)[T.10]                2.4332      0.012    202.107      0.000       2.410       2.457
C(Time)[T.11]                2.4563      0.012    203.940      0.000       2.433       2.480
C(Time)[T.12]                2.4469      0.012    203.191      0.000       2.423       2.470
C(Time)[T.13]                2.4976      0.012    207.590      0.000       2.474       2.521
C(Time)[T.14]                2.5479      0.012    211.683      0.000       2.524       2.572
C(Time)[T.15]                2.5705      0.012    213.647      0.000       2.547       2.594
C(Time)[T.16]                2.5463      0.012    211.802      0.000       2.523       2.570
C(Time)[T.17]                2.4055      0.012    200.071      0.000       2.382       2.429
C(Time)[T.18]                2.1542      0.012    179.070      0.000       2.131       2.178
C(Time)[T.19]                1.8344      0.012    152.336      0.000       1.811       1.858
C(Time)[T.20]                1.5388      0.012    127.691      0.000       1.515       1.562
C(Time)[T.21]                1.2086      0.012    100.333      0.000       1.185       1.232
C(Time)[T.22]                0.8169      0.012     67.799      0.000       0.793       0.840
C(Time)[T.23]                0.3908      0.012     32.430      0.000       0.367       0.414
C(WeightedMonth)[T.2]        0.0742      0.007     11.287      0.000       0.061       0.087
C(WeightedMonth)[T.3]       -0.0220      0.007     -3.291      0.001      -0.035      -0.009
C(WeightedMonth)[T.4]       -0.1396      0.006    -22.012      0.000      -0.152      -0.127
C(WeightedMonth)[T.5]       -0.0420      0.007     -6.373      0.000      -0.055      -0.029
C(WeightedMonth)[T.6]       -0.1386      0.006    -22.659      0.000      -0.151      -0.127
C(DayOfWeek)[T.2]           -0.1038      0.007    -15.943      0.000      -0.117      -0.091
C(DayOfWeek)[T.3]           -0.0813      0.006    -12.618      0.000      -0.094      -0.069
C(DayOfWeek)[T.4]            0.0330      0.007      5.056      0.000       0.020       0.046
C(DayOfWeek)[T.5]            0.2472      0.007     37.720      0.000       0.234       0.260
C(DayOfWeek)[T.6]            0.2186      0.007     33.193      0.000       0.206       0.232
C(DayOfWeek)[T.7]            0.1540      0.006     23.894      0.000       0.141       0.167
C(Condition_Code)[T.1.0]     0.0736      0.047      1.553      0.121      -0.019       0.166
C(Condition_Code)[T.2.0]     0.0681      0.081      0.842      0.400      -0.090       0.227
C(Condition_Code)[T.3.0]    -0.0634      0.024     -2.602      0.009      -0.111      -0.016
C(Condition_Code)[T.4.0]    -0.1058      0.125     -0.844      0.399      -0.351       0.140
C(Condition_Code)[T.5.0]    -0.2610      0.048     -5.426      0.000      -0.355      -0.167
C(Condition_Code)[T.6.0]    -0.1522      0.042     -3.638      0.000      -0.234      -0.070
C(Condition_Code)[T.7.0]    -0.1642      0.089     -1.854      0.064      -0.338       0.009
C(Condition_Code)[T.8.0]     0.0368      0.114      0.322      0.747      -0.187       0.261
C(Direction)[T.1]           -0.0801      0.003    -23.068      0.000      -0.087      -0.073
SNOW_DAY_SUM                 0.0001      0.000      0.363      0.716      -0.001       0.001
SNOW                              0          0        nan        nan           0           0
==============================================================================
Omnibus:                     9053.450   Durbin-Watson:                   2.508
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            56250.142
Skew:                          -0.696   Prob(JB):                         0.00
Kurtosis:                       7.905   Cond. No.                     1.32e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [22]:
data_with_snow['weights'] = 1 / data_with_snow['TRAFFIC']
data_with_snow['weights'] = data_with_snow['weights'].clip(upper=50)
wls = smf.wls(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_snow,
    weights=data_with_snow['weights']
).fit()

print(wls.summary())

C:\Users\wsach\AppData\Local\Temp\ipykernel_28904\3132579671.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_snow['weights'] = 1 / data_with_snow['TRAFFIC']
C:\Users\wsach\AppData\Local\Temp\ipykernel_28904\3132579671.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_snow['weights'] = data_with_snow['weights'].clip(upper=50)

                            WLS Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   R-squared:                       0.667
Model:                            WLS   Adj. R-squared:                  0.667
Method:                 Least Squares   F-statistic:                     1485.
Date:                Fri, 05 Dec 2025   Prob (F-statistic):               0.00
Time:                        10:23:18   Log-Likelihood:                -72141.
No. Observations:               36324   AIC:                         1.444e+05
Df Residuals:                   36274   BIC:                         1.448e+05
Df Model:                          49
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    5.6650      0.050    113.841      0.000       5.567       5.763
C(Time)[T.1]                -0.2163      0.049     -4.431      0.000      -0.312      -0.121
C(Time)[T.2]                -0.6141      0.047    -12.951      0.000      -0.707      -0.521
C(Time)[T.3]                -0.2958      0.049     -6.085      0.000      -0.391      -0.201
C(Time)[T.4]                -0.4581      0.048     -9.509      0.000      -0.553      -0.364
C(Time)[T.5]                 0.4573      0.051      9.019      0.000       0.358       0.557
C(Time)[T.6]                 0.9587      0.052     18.431      0.000       0.857       1.061
C(Time)[T.7]                 1.2459      0.053     23.649      0.000       1.143       1.349
C(Time)[T.8]                 1.3527      0.053     25.518      0.000       1.249       1.457
C(Time)[T.9]                 2.7639      0.060     45.921      0.000       2.646       2.882
C(Time)[T.10]                2.8673      0.060     47.505      0.000       2.749       2.986
C(Time)[T.11]                2.9148      0.061     48.153      0.000       2.796       3.033
C(Time)[T.12]                2.9183      0.061     48.155      0.000       2.800       3.037
C(Time)[T.13]                3.0077      0.061     49.670      0.000       2.889       3.126
C(Time)[T.14]                3.0348      0.061     49.905      0.000       2.916       3.154
C(Time)[T.15]                3.0362      0.061     49.848      0.000       2.917       3.156
C(Time)[T.16]                2.9971      0.061     49.274      0.000       2.878       3.116
C(Time)[T.17]                2.8395      0.060     46.966      0.000       2.721       2.958
C(Time)[T.18]                2.5884      0.060     43.385      0.000       2.471       2.705
C(Time)[T.19]                2.2426      0.059     38.174      0.000       2.127       2.358
C(Time)[T.20]                0.9148      0.053     17.346      0.000       0.811       1.018
C(Time)[T.21]                0.7128      0.052     13.658      0.000       0.611       0.815
C(Time)[T.22]                0.4896      0.052      9.490      0.000       0.388       0.591
C(Time)[T.23]               -1.0430      0.047    -21.982      0.000      -1.136      -0.950
C(WeightedMonth)[T.2]       -0.5119      0.033    -15.431      0.000      -0.577      -0.447
C(WeightedMonth)[T.3]       -2.1884      0.029    -75.409      0.000      -2.245      -2.132
C(WeightedMonth)[T.4]       -0.4598      0.035    -12.992      0.000      -0.529      -0.390
C(WeightedMonth)[T.5]       -0.1599      0.032     -4.959      0.000      -0.223      -0.097
C(WeightedMonth)[T.6]       -0.3222      0.043     -7.410      0.000      -0.407      -0.237
C(WeightedMonth)[T.7]       -0.1263      0.035     -3.652      0.000      -0.194      -0.059
C(WeightedMonth)[T.8]       -0.0106      0.186     -0.057      0.954      -0.374       0.353
C(WeightedMonth)[T.9]       -0.0233      0.045     -0.516      0.606      -0.112       0.065
C(WeightedMonth)[T.11]      -0.5197      0.150     -3.458      0.001      -0.814      -0.225
C(DayOfWeek)[T.2]           -0.1282      0.035     -3.713      0.000      -0.196      -0.061
C(DayOfWeek)[T.3]           -1.1175      0.033    -33.562      0.000      -1.183      -1.052
C(DayOfWeek)[T.4]           -1.8016      0.032    -56.868      0.000      -1.864      -1.739
C(DayOfWeek)[T.5]            0.2503      0.035      7.163      0.000       0.182       0.319
C(DayOfWeek)[T.6]            0.3104      0.035      8.923      0.000       0.242       0.379
C(DayOfWeek)[T.7]           -0.4905      0.035    -13.987      0.000      -0.559      -0.422
C(Condition_Code)[T.1.0]     0.4677      0.220      2.123      0.034       0.036       0.899
C(Condition_Code)[T.2.0]     0.8819      0.496      1.778      0.075      -0.090       1.854
C(Condition_Code)[T.3.0]     0.4725      0.079      5.947      0.000       0.317       0.628
C(Condition_Code)[T.4.0]     0.4991      0.466      1.071      0.284      -0.414       1.413
C(Condition_Code)[T.5.0]     0.1883      0.154      1.225      0.220      -0.113       0.490
C(Condition_Code)[T.6.0]     0.2314      0.083      2.797      0.005       0.069       0.394
C(Condition_Code)[T.7.0]     0.4136      0.158      2.621      0.009       0.104       0.723
C(Condition_Code)[T.8.0]     0.3571      0.268      1.333      0.182      -0.168       0.882
C(Direction)[T.1]           -0.2270      0.016    -13.836      0.000      -0.259      -0.195
SNOW_DAY_SUM                 0.0103      0.002      5.688      0.000       0.007       0.014
SNOW                        -0.1416      0.005    -29.110      0.000      -0.151      -0.132
==============================================================================
Omnibus:                    61936.508   Durbin-Watson:                   0.478
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        173081432.718
Skew:                         -11.363   Prob(JB):                         0.00
Kurtosis:                     340.405   Cond. No.                         581.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [24]:
glm_log = smf.glm(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_snow,
    family=sm.families.Gaussian(sm.families.links.log())
).fit()

print(glm_log.summary())

C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\genmod\families\links.py:13: FutureWarning: The log link alias is deprecated. Use Log instead. The log link alias will be removed after the 0.15.0 release.
  warnings.warn(

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   No. Observations:                36324
Model:                            GLM   Df Residuals:                    36274
Model Family:                Gaussian   Df Model:                           49
Link Function:                    log   Scale:                         0.22677
Method:                          IRLS   Log-Likelihood:                -24568.
Date:                Fri, 05 Dec 2025   Deviance:                       8226.0
Time:                        10:24:23   Pearson chi2:                 8.23e+03
No. Iterations:                     7   Pseudo R-squ. (CS):             0.9951
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    1.5981      0.003    543.593      0.000       1.592       1.604
C(Time)[T.1]                -0.0651      0.004    -17.596      0.000      -0.072      -0.058
C(Time)[T.2]                -0.1041      0.004    -27.523      0.000      -0.112      -0.097
C(Time)[T.3]                -0.0907      0.004    -24.158      0.000      -0.098      -0.083
C(Time)[T.4]                -0.0100      0.004     -2.777      0.005      -0.017      -0.003
C(Time)[T.5]                 0.1370      0.003     40.816      0.000       0.130       0.144
C(Time)[T.6]                 0.2759      0.003     86.917      0.000       0.270       0.282
C(Time)[T.7]                 0.3520      0.003    114.028      0.000       0.346       0.358
C(Time)[T.8]                 0.3764      0.003    122.830      0.000       0.370       0.382
C(Time)[T.9]                 0.3928      0.003    128.677      0.000       0.387       0.399
C(Time)[T.10]                0.4059      0.003    133.603      0.000       0.400       0.412
C(Time)[T.11]                0.4131      0.003    136.266      0.000       0.407       0.419
C(Time)[T.12]                0.4133      0.003    136.265      0.000       0.407       0.419
C(Time)[T.13]                0.4201      0.003    138.918      0.000       0.414       0.426
C(Time)[T.14]                0.4274      0.003    141.613      0.000       0.421       0.433
C(Time)[T.15]                0.4292      0.003    142.213      0.000       0.423       0.435
C(Time)[T.16]                0.4250      0.003    140.619      0.000       0.419       0.431
C(Time)[T.17]                0.4040      0.003    132.797      0.000       0.398       0.410
C(Time)[T.18]                0.3673      0.003    119.415      0.000       0.361       0.373
C(Time)[T.19]                0.3183      0.003    101.766      0.000       0.312       0.324
C(Time)[T.20]                0.2732      0.003     85.947      0.000       0.267       0.279
C(Time)[T.21]                0.2214      0.003     68.274      0.000       0.215       0.228
C(Time)[T.22]                0.1560      0.003     46.823      0.000       0.150       0.163
C(Time)[T.23]                0.0771      0.003     22.338      0.000       0.070       0.084
C(WeightedMonth)[T.2]        0.0070      0.001      4.925      0.000       0.004       0.010
C(WeightedMonth)[T.3]       -0.0069      0.001     -5.177      0.000      -0.010      -0.004
C(WeightedMonth)[T.4]       -0.0267      0.002    -17.471      0.000      -0.030      -0.024
C(WeightedMonth)[T.5]       -0.0042      0.001     -3.090      0.002      -0.007      -0.002
C(WeightedMonth)[T.6]       -0.0347      0.002    -18.522      0.000      -0.038      -0.031
C(WeightedMonth)[T.7]       -0.0334      0.001    -22.533      0.000      -0.036      -0.030
C(WeightedMonth)[T.8]        0.0153      0.007      2.094      0.036       0.001       0.030
C(WeightedMonth)[T.9]       -0.0314      0.002    -16.152      0.000      -0.035      -0.028
C(WeightedMonth)[T.11]       0.0084      0.006      1.365      0.172      -0.004       0.020
C(DayOfWeek)[T.2]           -0.0203      0.002    -13.515      0.000      -0.023      -0.017
C(DayOfWeek)[T.3]           -0.0101      0.002     -6.612      0.000      -0.013      -0.007
C(DayOfWeek)[T.4]            0.0066      0.001      4.448      0.000       0.004       0.010
C(DayOfWeek)[T.5]            0.0399      0.001     27.346      0.000       0.037       0.043
C(DayOfWeek)[T.6]            0.0321      0.001     21.916      0.000       0.029       0.035
C(DayOfWeek)[T.7]            0.0259      0.002     16.774      0.000       0.023       0.029
C(Condition_Code)[T.1.0]    -0.0014      0.008     -0.173      0.862      -0.017       0.014
C(Condition_Code)[T.2.0]     0.0237      0.018      1.291      0.197      -0.012       0.060
C(Condition_Code)[T.3.0]    -0.0130      0.003     -4.137      0.000      -0.019      -0.007
C(Condition_Code)[T.4.0]    -0.0068      0.017     -0.402      0.688      -0.040       0.026
C(Condition_Code)[T.5.0]    -0.0375      0.007     -5.690      0.000      -0.050      -0.025
C(Condition_Code)[T.6.0]    -0.0412      0.003    -12.141      0.000      -0.048      -0.035
C(Condition_Code)[T.7.0]    -0.0454      0.007     -6.825      0.000      -0.058      -0.032
C(Condition_Code)[T.8.0]    -0.0339      0.013     -2.686      0.007      -0.059      -0.009
C(Direction)[T.1]           -0.0177      0.001    -22.757      0.000      -0.019      -0.016
SNOW_DAY_SUM              1.613e-05   7.77e-05      0.208      0.836      -0.000       0.000
SNOW                        -0.0045      0.000    -20.261      0.000      -0.005      -0.004
============================================================================================

In [26]:
glm_gamma = smf.glm(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_snow,
    family=sm.families.Gamma()
).fit()

print(glm_gamma.summary())

C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\genmod\generalized_linear_model.py:308: DomainWarning: The InversePower link function does not respect the domain of the Gamma family.
  warnings.warn((f"The {type(family.link).__name__} link function "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   No. Observations:                36324
Model:                            GLM   Df Residuals:                    36274
Model Family:                   Gamma   Df Model:                           49
Link Function:           InversePower   Scale:                       0.0062314
Method:                          IRLS   Log-Likelihood:                    inf
Date:                Fri, 05 Dec 2025   Deviance:                       2376.6
Time:                        10:27:51   Pearson chi2:                     226.
No. Iterations:                     7   Pseudo R-squ. (CS):                nan
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    0.2029      0.000    416.197      0.000       0.202       0.204
C(Time)[T.1]                 0.0138      0.001     22.551      0.000       0.013       0.015
C(Time)[T.2]                 0.0225      0.001     35.911      0.000       0.021       0.024
C(Time)[T.3]                 0.0195      0.001     31.254      0.000       0.018       0.021
C(Time)[T.4]                 0.0019      0.001      3.269      0.001       0.001       0.003
C(Time)[T.5]                -0.0264      0.001    -47.428      0.000      -0.027      -0.025
C(Time)[T.6]                -0.0496      0.001    -94.217      0.000      -0.051      -0.049
C(Time)[T.7]                -0.0611      0.001   -119.298      0.000      -0.062      -0.060
C(Time)[T.8]                -0.0646      0.001   -127.099      0.000      -0.066      -0.064
C(Time)[T.9]                -0.0669      0.001   -132.192      0.000      -0.068      -0.066
C(Time)[T.10]               -0.0687      0.001   -136.449      0.000      -0.070      -0.068
C(Time)[T.11]               -0.0697      0.001   -138.711      0.000      -0.071      -0.069
C(Time)[T.12]               -0.0698      0.001   -138.716      0.000      -0.071      -0.069
C(Time)[T.13]               -0.0707      0.001   -141.012      0.000      -0.072      -0.070
C(Time)[T.14]               -0.0717      0.001   -143.240      0.000      -0.073      -0.071
C(Time)[T.15]               -0.0719      0.001   -143.740      0.000      -0.073      -0.071
C(Time)[T.16]               -0.0714      0.001   -142.416      0.000      -0.072      -0.070
C(Time)[T.17]               -0.0685      0.001   -135.799      0.000      -0.069      -0.068
C(Time)[T.18]               -0.0633      0.001   -124.221      0.000      -0.064      -0.062
C(Time)[T.19]               -0.0562      0.001   -108.282      0.000      -0.057      -0.055
C(Time)[T.20]               -0.0492      0.001    -93.408      0.000      -0.050      -0.048
C(Time)[T.21]               -0.0409      0.001    -76.066      0.000      -0.042      -0.040
C(Time)[T.22]               -0.0298      0.001    -53.864      0.000      -0.031      -0.029
C(Time)[T.23]               -0.0153      0.001    -26.773      0.000      -0.016      -0.014
C(WeightedMonth)[T.2]       -0.0011      0.000     -4.741      0.000      -0.002      -0.001
C(WeightedMonth)[T.3]        0.0011      0.000      5.141      0.000       0.001       0.002
C(WeightedMonth)[T.4]        0.0040      0.000     15.644      0.000       0.003       0.004
C(WeightedMonth)[T.5]        0.0007      0.000      2.962      0.003       0.000       0.001
C(WeightedMonth)[T.6]        0.0051      0.000     16.474      0.000       0.005       0.006
C(WeightedMonth)[T.7]        0.0051      0.000     20.612      0.000       0.005       0.006
C(WeightedMonth)[T.8]       -0.0027      0.001     -2.249      0.024      -0.005      -0.000
C(WeightedMonth)[T.9]        0.0045      0.000     13.945      0.000       0.004       0.005
C(WeightedMonth)[T.11]      -0.0014      0.001     -1.406      0.160      -0.003       0.001
C(DayOfWeek)[T.2]            0.0031      0.000     12.456      0.000       0.003       0.004
C(DayOfWeek)[T.3]            0.0015      0.000      5.888      0.000       0.001       0.002
C(DayOfWeek)[T.4]           -0.0011      0.000     -4.410      0.000      -0.002      -0.001
C(DayOfWeek)[T.5]           -0.0060      0.000    -24.893      0.000      -0.006      -0.006
C(DayOfWeek)[T.6]           -0.0048      0.000    -19.820      0.000      -0.005      -0.004
C(DayOfWeek)[T.7]           -0.0035      0.000    -13.802      0.000      -0.004      -0.003
C(Condition_Code)[T.1.0]     0.0002      0.001      0.141      0.888      -0.002       0.003
C(Condition_Code)[T.2.0]    -0.0037      0.003     -1.205      0.228      -0.010       0.002
C(Condition_Code)[T.3.0]     0.0018      0.001      3.435      0.001       0.001       0.003
C(Condition_Code)[T.4.0]     0.0011      0.003      0.392      0.695      -0.004       0.007
C(Condition_Code)[T.5.0]     0.0057      0.001      5.215      0.000       0.004       0.008
C(Condition_Code)[T.6.0]     0.0060      0.001     10.606      0.000       0.005       0.007
C(Condition_Code)[T.7.0]     0.0065      0.001      5.914      0.000       0.004       0.009
C(Condition_Code)[T.8.0]     0.0055      0.002      2.617      0.009       0.001       0.010
C(Direction)[T.1]            0.0035      0.000     26.980      0.000       0.003       0.004
SNOW_DAY_SUM             -6.281e-06   1.29e-05     -0.488      0.626   -3.15e-05     1.9e-05
SNOW                         0.0007   3.72e-05     19.005      0.000       0.001       0.001
============================================================================================

C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\genmod\families\family.py:812: RuntimeWarning: divide by zero encountered in log
  ll_obs -= special.gammaln(weight_scale) + np.log(endog)
C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\genmod\generalized_linear_model.py:1891: RuntimeWarning: invalid value encountered in scalar subtract
  prsq = 1 - np.exp((self.llnull - self.llf) * (2 / self.nobs))

In [29]:
glm_nb = smf.glm(
    formula="TRAFFIC ~ C(Time) + C(WeightedMonth) + C(DayOfWeek) + SNOW_DAY_SUM + C(Condition_Code) + C(Direction) + SNOW",
    data=data_with_snow,
    family=sm.families.NegativeBinomial()
).fit()

print(glm_nb.summary())

C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\genmod\families\family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                TRAFFIC   No. Observations:                36324
Model:                            GLM   Df Residuals:                    36274
Model Family:        NegativeBinomial   Df Model:                           49
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -1.0562e+05
Date:                Fri, 05 Dec 2025   Deviance:                       286.13
Time:                        10:29:12   Pearson chi2:                     191.
No. Iterations:                     5   Pseudo R-squ. (CS):            0.02785
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    1.6021      0.036     44.815      0.000       1.532       1.672
C(Time)[T.1]                -0.0650      0.040     -1.618      0.106      -0.144       0.014
C(Time)[T.2]                -0.1038      0.040     -2.575      0.010      -0.183      -0.025
C(Time)[T.3]                -0.0901      0.040     -2.237      0.025      -0.169      -0.011
C(Time)[T.4]                -0.0093      0.040     -0.231      0.817      -0.088       0.069
C(Time)[T.5]                 0.1372      0.040      3.444      0.001       0.059       0.215
C(Time)[T.6]                 0.2751      0.040      6.947      0.000       0.197       0.353
C(Time)[T.7]                 0.3513      0.039      8.916      0.000       0.274       0.428
C(Time)[T.8]                 0.3760      0.039      9.543      0.000       0.299       0.453
C(Time)[T.9]                 0.3929      0.039      9.954      0.000       0.316       0.470
C(Time)[T.10]                0.4062      0.039     10.309      0.000       0.329       0.483
C(Time)[T.11]                0.4137      0.039     10.496      0.000       0.336       0.491
C(Time)[T.12]                0.4140      0.039     10.497      0.000       0.337       0.491
C(Time)[T.13]                0.4210      0.039     10.696      0.000       0.344       0.498
C(Time)[T.14]                0.4283      0.039     10.877      0.000       0.351       0.506
C(Time)[T.15]                0.4303      0.039     10.917      0.000       0.353       0.507
C(Time)[T.16]                0.4261      0.039     10.807      0.000       0.349       0.503
C(Time)[T.17]                0.4050      0.039     10.261      0.000       0.328       0.482
C(Time)[T.18]                0.3681      0.039      9.324      0.000       0.291       0.445
C(Time)[T.19]                0.3187      0.040      8.054      0.000       0.241       0.396
C(Time)[T.20]                0.2734      0.040      6.898      0.000       0.196       0.351
C(Time)[T.21]                0.2216      0.040      5.579      0.000       0.144       0.299
C(Time)[T.22]                0.1562      0.040      3.918      0.000       0.078       0.234
C(Time)[T.23]                0.0774      0.040      1.936      0.053      -0.001       0.156
C(WeightedMonth)[T.2]        0.0079      0.021      0.376      0.707      -0.033       0.049
C(WeightedMonth)[T.3]       -0.0080      0.020     -0.409      0.683      -0.047       0.031
C(WeightedMonth)[T.4]       -0.0248      0.022     -1.113      0.266      -0.068       0.019
C(WeightedMonth)[T.5]       -0.0046      0.020     -0.228      0.820      -0.044       0.035
C(WeightedMonth)[T.6]       -0.0316      0.027     -1.172      0.241      -0.084       0.021
C(WeightedMonth)[T.7]       -0.0320      0.021     -1.495      0.135      -0.074       0.010
C(WeightedMonth)[T.8]        0.0223      0.111      0.200      0.841      -0.195       0.240
C(WeightedMonth)[T.9]       -0.0268      0.028     -0.958      0.338      -0.082       0.028
C(WeightedMonth)[T.11]       0.0108      0.091      0.119      0.906      -0.168       0.190
C(DayOfWeek)[T.2]           -0.0193      0.021     -0.899      0.369      -0.061       0.023
C(DayOfWeek)[T.3]           -0.0092      0.022     -0.419      0.675      -0.052       0.034
C(DayOfWeek)[T.4]            0.0073      0.022      0.338      0.735      -0.035       0.050
C(DayOfWeek)[T.5]            0.0393      0.021      1.835      0.067      -0.003       0.081
C(DayOfWeek)[T.6]            0.0310      0.021      1.447      0.148      -0.011       0.073
C(DayOfWeek)[T.7]            0.0202      0.022      0.899      0.369      -0.024       0.064
C(Condition_Code)[T.1.0]    -0.0022      0.126     -0.017      0.986      -0.250       0.246
C(Condition_Code)[T.2.0]     0.0225      0.286      0.079      0.937      -0.539       0.584
C(Condition_Code)[T.3.0]    -0.0114      0.047     -0.240      0.810      -0.104       0.082
C(Condition_Code)[T.4.0]    -0.0047      0.268     -0.018      0.986      -0.529       0.520
C(Condition_Code)[T.5.0]    -0.0366      0.095     -0.385      0.700      -0.223       0.150
C(Condition_Code)[T.6.0]    -0.0396      0.050     -0.791      0.429      -0.138       0.058
C(Condition_Code)[T.7.0]    -0.0427      0.096     -0.444      0.657      -0.231       0.146
C(Condition_Code)[T.8.0]    -0.0352      0.172     -0.205      0.838      -0.371       0.301
C(Direction)[T.1]           -0.0274      0.011     -2.425      0.015      -0.050      -0.005
SNOW_DAY_SUM              6.642e-05      0.001      0.059      0.953      -0.002       0.002
SNOW                        -0.0046      0.003     -1.423      0.155      -0.011       0.002
============================================================================================

In [30]:
from sklearn.linear_model import LassoCV

X = pd.get_dummies(data_with_snow.drop(columns=['TRAFFIC']), drop_first=True)
y = data_with_snow['TRAFFIC']

lasso = LassoCV(cv=5).fit(X, y)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.BoolDType'>)

In [31]:
model = sm.tsa.SARIMAX(
    data_with_snow.TRAFFIC,
    exog=data_with_snow[['SNOW', 'SNOW_DAY_SUM']],
    order=(1,0,1),
    seasonal_order=(1,0,1,24)
).fit()

C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
C:\Users\wsach\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "